name: CI/CD for Trash Classification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set WANDB_API_KEY
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      run: wandb login $WANDB_API_KEY

    - name: Run tests
      run: |
        python src/train.py
        python src/evaluate.py

    - name: Upload Model
      uses: actions/upload-artifact@v4
      with:
        name: model
        path: weight/best_model.pth
